version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: Europe/Berlin
  labels:
  - L - Awaiting reviews
  - dependencies
  versioning-strategy: increase
